zinzi/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from config.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', index, name='index'),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^reservations/', include('reservations.urls', namespace='reservations')),
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

zinzi/reservations/urls.py
from django.conf.urls import url

from reservations.apis import test
from reservations.apis.favorites import RestaurantFavoriteToggle, CustomerFavoriteListView
from reservations.apis.payments import PaymentCreateView, PaymentDetailUpdateView, PaymentCancelCreateDetailView, \
    PaymentListView
from reservations.apis.reservations import ReservationCreateView, ReservationPatchView, CustomerReservationListView, \
    CustomerReservationDetailView, RestaurantReservationListView, RestaurantReservationDetailView, \
    CustomerReservationListByDateView, RestaurantReservationListByDateView
from reservations.apis.statistics import PaymentRateView, ReservationMVPView

urlpatterns = [
    # 예약정보 url
    url(r'^(?P<pk>\d+)/reservation/$', ReservationCreateView.as_view(), name='reservation-create'),
    url(r'^(?P<pk>\d+)/reservation/addinfo/$', ReservationPatchView.as_view(), name='reservation-patch'),

    url(r'^customer/$', CustomerReservationListView.as_view(), name='customer-reservation-list'),
    url(r'^(?P<pk>\d+)/customer/$', CustomerReservationDetailView.as_view(), name='customer-reservation-detail'),

    url(r'^(?P<pk>\d+)/restaurant/$', RestaurantReservationListView.as_view(), name='restaurant-reservation-list'),
    url(r'^(?P<pk>\d+)/restaurant/(?P<imp_uid>imp_\d+)/$',
        RestaurantReservationDetailView.as_view(),
        name='restaurant-reservation-detail'),

    url(r'^customer/date/$', CustomerReservationListByDateView.as_view(), name='customer-reservation-list-by-date'),
    url(r'^(?P<pk>\d+)/restaurant/date/$', RestaurantReservationListByDateView.as_view(),
        name='restaurant-reservation-list-by-date'),

    # 결제정보 url
    url(r'^(?P<pk>\d+)/payment/$', PaymentCreateView.as_view(), name='payment-create'),
    url(r'^payment/$', PaymentListView.as_view(), name='payment-list'),
    url(r'^(?P<imp_uid>imp_\d+)/payment/$', PaymentDetailUpdateView.as_view(), name='payment-detailupdate'),

    url(r'^(?P<imp_uid>imp_\d+)/paymentcancel/$', PaymentCancelCreateDetailView.as_view(),
        name='paymentcancel-createdetail'),

    # 통계
    url(r'^(?P<pk>\d+)/rate/$', PaymentRateView.as_view(), name='payment-rate'),
    url(r'^(?P<pk>\d+)/mvp/$', ReservationMVPView.as_view(), name='reservation-mvp'),

    # 즐겨찾기
    url(r'^(?P<pk>\d+)/favorite-toggle/$', RestaurantFavoriteToggle.as_view(), name='favorite-toggle'),

    url(r'^favorite-toggle/$', CustomerFavoriteListView.as_view(), name='customer-favorite'),

    # 결제 테스트용 url
    url(r'^test/$', test)
]

zinzi/reservations/models.py
from django.db import models

from accounts.models import User
from restaurants.models import ReservationInfo, Restaurant


class Reservation(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
    )
    information = models.ForeignKey(
        ReservationInfo,
        on_delete=models.PROTECT,
    )
    restaurant = models.ForeignKey(
        Restaurant,
        on_delete=models.PROTECT,
    )
    name = models.CharField(max_length=10, blank=True, null=True)
    party = models.PositiveSmallIntegerField()
    price = models.PositiveIntegerField()
    phone_number = models.CharField(max_length=11, blank=True, null=True)
    email = models.CharField(max_length=30, blank=True, null=True)
    status = models.CharField(max_length=10, default='paid')

    def __str__(self):
        return f'reservation_pk:{self.pk} information_pk{self.information.pk}'


class Payment(models.Model):
    # 고유번호
    imp_uid = models.CharField(max_length=50)
    merchant_uid = models.CharField(max_length=50)
    # 지불방법 및 pg사 정보
    pay_method = models.CharField(max_length=20)
    pg_provider = models.CharField(max_length=20)
    pg_tid = models.CharField(max_length=50)
    # 주문정보
    name = models.CharField(max_length=50)
    amount = models.IntegerField()
    cancel_amount = models.IntegerField()
    currency = models.CharField(max_length=5)
    status = models.CharField(max_length=10)
    paid_at = models.IntegerField()
    failed_at = models.IntegerField()
    cancelled_at = models.IntegerField()
    fail_reason = models.CharField(max_length=255, null=True, blank=True)
    cancel_reason = models.CharField(max_length=255, null=True, blank=True)
    # 주문자 정보
    buyer_name = models.CharField(max_length=10)
    buyer_email = models.CharField(max_length=30)
    buyer_tel = models.CharField(max_length=20)
    # Reservation 모델 연결
    reservation = models.OneToOneField(
        Reservation,
        on_delete=models.PROTECT,
    )

    def __str__(self):
        return f'payment_pk:{self.pk} reservation_pk:{self.reservation.pk}'


class PaymentCancel(models.Model):
    payment = models.OneToOneField(
        Payment,
        on_delete=models.CASCADE,
    )
    reason = models.CharField(max_length=50)

zinzi/reservations/urls/views.py
from django.conf.urls import url

from reservations.views.payment import payment_view, payment_reservations_save_view, payment_complete_view, \
    payment_cancel_request_view, payment_cancel_confirm_view
from reservations.views.reservations import reservation_view, reservation_check_view, reservation_check_detail_view

urlpatterns = [
    url(r'^(?P<pk>\d+)/$', reservation_view, name='reservation'),

    url(r'^payment/$', payment_view, name='payment'),
    url(r'^payment/save/$', payment_reservations_save_view, name='save_all'),
    url(r'^payment/complete/$', payment_complete_view, name='complete'),

    url(r'^paymentcancel/(?P<pk>\d+)/$', payment_cancel_request_view, name='payment_cancel'),
    url(r'^paymentcancel/confirm/(?P<pk>\d+)/$', payment_cancel_confirm_view, name='payment_cancel_confirm'),

    url(r'^check/$', reservation_check_view, name='reservation_check'),
    url(r'^check/(?P<pk>\d+)/$', reservation_check_detail_view, name='reservation_check_detail'),
]

zinzi/reservations/views/favorite.py
from rest_framework import generics
from rest_framework.response import Response

from accounts.serializers import UserSerializer
from restaurants.models import Restaurant
from restaurants.serializers import RestaurantListSerializer


# 즐겨찾기
class RestaurantFavoriteToggle(generics.GenericAPIView):
    queryset = Restaurant.objects.all()

    def post(self, request, *args, **kwargs):
        instance = self.get_object()
        user = request.user
        if user.profile.favorites.filter(pk=instance.pk):
            user.profile.favorites.remove(instance)
            favorite_status = False
        else:
            user.profile.favorites.add(instance)
            favorite_status = True
        data = {
            'user': UserSerializer(user).data,
            'Restaurant': RestaurantListSerializer(instance).data,
            'result': favorite_status,
        }
        return Response(data)

zinzi/reservations/views/payment.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core import exceptions
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from iamport import Iamport

from reservations.forms import PaymentCancelForm
from reservations.models import Reservation, Payment
from restaurants.models import ReservationInfo, Restaurant

User = get_user_model()


@login_required
def payment_view(request):
    if request.method == 'POST':
        restaurant = request.POST.get('restaurant')
        information = request.POST.get('information')
        information_pk = request.POST.get('information_pk')
        name = request.POST.get('name')
        party = request.POST.get('party')
        phone_number = request.POST.get('phone_number')
        email = request.POST.get('email')
        price = request.POST.get('price')
        restaurant_pk = request.POST.get('restaurant_pk')
        context = {
            'restaurant': restaurant,
            'information': information,
            'name': name,
            'party': party,
            'phone_number': phone_number,
            'email': email,
            'price': price,
            'information_pk': information_pk,
            'restaurant_pk': restaurant_pk,
        }
        return render(request, 'reservation/payment.html', context)
    else:
        raise Http404


@login_required
def payment_reservations_save_view(request):
    if request.method == 'POST':
        restaurant = int(request.POST.get('restaurant'))
        information = int(request.POST.get('information'))
        name = request.POST.get('name')
        party = int(request.POST.get('party'))
        phone_number = int(request.POST.get('phone_number'))
        email = request.POST.get('email')
        price = int(request.POST.get('price'))
        reservation = Reservation.objects.create(
            user=request.user,
            information=get_object_or_404(ReservationInfo, pk=information),
            restaurant=get_object_or_404(Restaurant, pk=restaurant),
            name=name,
            party=party,
            phone_number=phone_number,
            email=email,
            price=price,
        )
        # 예약 가능 인원 수에서 예약 인원만큼 빼 줌
        get_object_or_404(ReservationInfo, pk=information).acceptable_size_of_party_update(party)
        iamport = Iamport(imp_key=settings.IMP_KEY,
                          imp_secret=settings.IMP_SECRET)
        # 입력한 imp_uid로부터 결제정보를 가져옴
        payment = iamport.find(imp_uid=request.POST.get('imp_uid'))
        # Payment 모델에 있는 모든 필드를 리스트에 담음
        all_fields = [f.name for f in Payment._meta.get_fields()]
        # 주문 해야할 금액과 실제 결제 금액이 일치하는지 검증 후 일치하지 않으면 자동으로 취소
        # 취소 되었을 경우에는 취소 되어진 결제정보로 데이터베이스에 저장
        # 또한, 취소 되었을 경우 취소되었다는 메일 보냄(celery로 비동기 처리, celery config dev로 바꾸고 배포 관련 처리 하고 주석 빼야 함)
        if not iamport.is_paid(int(request.POST.get('price')), imp_uid=request.POST.get('imp_uid')):
            cancel = iamport.cancel(u'가격 불일치', imp_uid=request.POST.get('imp_uid'))
            # send_mail_task.delay('Test', 'Test', 'darkblank1990@gmail.com')
            Payment.objects.create(
                **{key: value for key, value in cancel.items() if key in all_fields},
                reservation=reservation
            )
        else:
            Payment.objects.create(
                **{key: value for key, value in payment.items() if key in all_fields},
                reservation=reservation
            )
            return HttpResponse('success')
        return HttpResponse('failed')


@login_required()
def payment_complete_view(request):
    reservation = Reservation.objects.filter(user=request.user)
    info = reservation.last()
    context = {
        'info': info,
    }
    return render(request, 'reservation/complete.html', context)


@login_required()
def payment_cancel_request_view(request, pk):
    payment = get_object_or_404(Payment, pk=pk)
    if request.method == 'POST':
        form = PaymentCancelForm(request.POST)
        if form.is_valid():
            cancel = form.save(commit=False)
            cancel.payment = payment
            payment.reservation.status = 'cancel request'
            payment.reservation.save()
            cancel.save()
        return redirect('reservations:views:reservation_check_detail', pk=payment.reservation.pk)
    else:
        form = PaymentCancelForm()
    context = {
        'form': form,
    }
    return render(request, 'reservation/cancel.html', context)


@login_required()
def payment_cancel_confirm_view(request, pk):
    payment = get_object_or_404(Payment, pk=pk)
    iamport = Iamport(imp_key=settings.IMP_KEY,
                      imp_secret=settings.IMP_SECRET)
    # 입력한 취소 사유로 해당 imp_uid의 결제 취소 진행
    # Iamport.ResponseError > 이미 결제 취소되어진 경우
    try:
        cancel = iamport.cancel(payment.paymentcancel.reason, imp_uid=payment.imp_uid)
    except Iamport.ResponseError:
        raise exceptions.PermissionDenied('Already cancelled')
    all_fields = [f.name for f in Payment._meta.get_fields()]
    Payment.objects.filter(pk=pk).update(
        **{key: value for key, value in cancel.items() if key in all_fields},
    )
    payment.reservation.status = 'cancelled'
    payment.reservation.save()
    return redirect('reservations:views:reservation_check_detail', pk=payment.reservation.pk)

zinzi/reservations/views/payments.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.utils.datastructures import MultiValueDictKeyError
from iamport import Iamport
from rest_framework import exceptions
from rest_framework import status, generics
from rest_framework.response import Response
from rest_framework.views import APIView

from reservations.models import Reservation, Payment
from reservations.serializers.payments import PaymentSerializer, PaymentCancelSerializer

User = get_user_model()


# 가격 불일치시 메일이나 문자 보내주는 메서드도 추가 필요
# status==paid 인지 확인 필요
class PaymentCreateView(APIView):
    def post(self, request, pk):
        reservation = get_object_or_404(Reservation, pk=pk)
        iamport = Iamport(imp_key=settings.IMP_KEY,
                          imp_secret=settings.IMP_SECRET)
        # 입력한 imp_uid로부터 결제정보를 가져옴
        payment = iamport.find(imp_uid=request.data.get('imp_uid'))
        # 주문 해야할 금액과 실제 결제 금액이 일치하는지 검증 후 일치하지 않으면 자동으로 취소
        # 취소 되었을 경우에는 취소 되어진 결제정보로 데이터베이스에 저장
        # 또한, 취소 되었을 경우 취소되었다는 메일 보냄(celery로 비동기 처리, celery config dev로 바꾸고 배포 관련 처리 하고 주석 빼야 함)
        if not iamport.is_paid(int(request.data.get('price')), imp_uid=request.data.get('imp_uid')):
            cancel = iamport.cancel(u'가격 불일치', imp_uid=request.data.get('imp_uid'))
            # send_mail_task.delay('Test', 'Test', 'darkblank1990@gmail.com')
            serializer = PaymentSerializer(data=cancel)
        else:
            serializer = PaymentSerializer(data=payment)
        if serializer.is_valid(raise_exception=True):
            try:
                serializer.save(reservation=reservation)
            except IntegrityError:
                raise exceptions.ValidationError
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class PaymentListView(generics.ListAPIView):
    queryset = Payment.objects.all()
    serializer_class = PaymentSerializer


class PaymentDetailUpdateView(APIView):
    def patch(self, request, imp_uid):
        payment = get_object_or_404(Payment, imp_uid=imp_uid)
        iamport = Iamport(imp_key=settings.IMP_KEY,
                          imp_secret=settings.IMP_SECRET)
        # 입력한 취소 사유로 해당 imp_uid의 결제 취소 진행
        # Iamport.ResponseError > 이미 결제 취소되어진 경우
        try:
            cancel = iamport.cancel(request.data['reason'], imp_uid=payment.imp_uid)
        except Iamport.ResponseError:
            raise exceptions.NotAcceptable('Already cancelled')
        except MultiValueDictKeyError:
            raise exceptions.ValidationError
        serializer = PaymentSerializer(payment, data=cancel, partial=True)
        # 결제 취소가 이루어지면 해당 결제 정보에 연결된 예약 정보의 status 필드를 cancelled로 변경
        if serializer.is_valid(raise_exception=True):
            serializer.save()
            payment.reservation.status = 'cancelled'
            payment.reservation.save()
            return Response(serializer.data, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, imp_uid):
        payment = get_object_or_404(Payment, imp_uid=imp_uid)
        serializer = PaymentSerializer(payment)
        return Response(serializer.data)


class PaymentCancelCreateDetailView(APIView):
    def post(self, request, imp_uid):
        payment = get_object_or_404(Payment, imp_uid=imp_uid)
        serializer = PaymentCancelSerializer(data=request.data)
        # 결제 취소 요청 정보를 입력하면 연결된 예약 정보의 status 필드를 request로 변경
        if serializer.is_valid(raise_exception=True):
            try:
                serializer.save(payment=payment)
                payment.reservation.status = 'request'
                payment.reservation.save()
            except IntegrityError:
                raise exceptions.ValidationError
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

    def get(self, request, imp_uid):
        payment = get_object_or_404(Payment, imp_uid=imp_uid)
        data = PaymentCancelSerializer(payment.paymentcancel).data
        return Response(data)

zinzi/templates/reservation/cancel.html
{% extends 'base.html' %}

{% block content %}
    {% include 'include/form-horizontal.html' with form=form submit_text='취소 요청' %}
{% endblock %}

zinzi/templates/reservation/check.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <ul class="list-group" style="height: auto;">
            <li class="list-group-item">레스토랑 이름: {{ restaurant }}</li>
            <li class="list-group-item">날짜: {{ information.date }}</li>
            <li class="list-group-item">시간: {{ information.time }}</li>
            <li class="list-group-item">예약자: {{ name }}</li>
            <li class="list-group-item">인원: {{ party }}</li>
            <li class="list-group-item">핸드폰 번호: {{ phone_number }}</li>
            <li class="list-group-item">email: {{ email }}</li>
            <li class="list-group-item">총 가격: {{ price }}</li>
        </ul>
    </div>
    <div class="row">위의 내용이 맞으시면 아래 결제 버튼을 눌러주세요.</div>
    <form action="{% url 'reservations:views:payment' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="restaurant" value="{{ restaurant }}">
        <input type="hidden" name="information" value="{{ information }}">
        <input type="hidden" name="name" value="{{ name }}">
        <input type="hidden" name="party" value="{{ party }}">
        <input type="hidden" name="phone_number" value="{{ phone_number }}">
        <input type="hidden" name="email" value="{{ email }}">
        <input type="hidden" name="price" value="{{ price }}">
        <input type="hidden" name="information_pk" value="{{ information.pk }}">
        <input type="hidden" name="restaurant_pk" value="{{ restaurant.pk }}">
    <input class="row" type="submit" value="결제">
</form>
{% endblock %}

zinzi/templates/reservation/complete.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <ul class="list-group" style="height: auto;">
            <li class="list-group-item">레스토랑 이름: {{ info.restaurant }}</li>
            <li class="list-group-item">날짜 및 시간: {{ info.information }}</li>
            <li class="list-group-item">예약자: {{ info.name }}</li>
            <li class="list-group-item">인원: {{ info.party }}</li>
            <li class="list-group-item">핸드폰 번호: {{ info.phone_number }}</li>
            <li class="list-group-item">email: {{ info.email }}</li>
            <li class="list-group-item">총 가격: {{ info.price }}</li>
        </ul>
    </div>
    <div class="row">위의 내용으로 결제가 완료 되었습니다.</div>
{% endblock %}

zinzi/templates/reservation/customer_reservation_detail.html
{% extends 'base.html' %}

{% block content %}
    <div>
        restaurant: {{ reservation.restaurant }}
    </div>
    <div>
        information: {{ reservation.information }}
    </div>
    <div>
        name: {{ reservation.name }}
    </div>
    <div>
        party: {{ reservation.party }}
    </div>
    <div>
        price: {{ reservation.price }}
    </div>
    <div>
        status: {{ reservation.status }}
    </div>
{% endblock %}

zinzi/templates/reservation/owner_reservation.html
{% extends 'base.html' %}

{% block content %}
    {% for reservation in reservations %}
        <div>
            <a href="{% url 'reservations:views:owner_reservation_detail' pk=reservation.pk %}">
                <div>
                    {{ reservation.information }}
                </div>
                <div>
                    {{ reservation.name }}
                </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}

zinzi/templates/reservation/payment.html
{% extends 'base.html' %}
{% block head %}
<script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js" ></script>
<script type="text/javascript" src="https://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
{% endblock %}
{% block content %}
    <div class="row">
        <ul class="list-group" style="height: auto;">
            <li class="list-group-item">레스토랑 이름: {{ restaurant }}</li>
            <li class="list-group-item">날짜 및 시간: {{ information }}</li>
            <li class="list-group-item">예약자: {{ name }}</li>
            <li class="list-group-item">인원: {{ party }}</li>
            <li class="list-group-item">핸드폰 번호: {{ phone_number }}</li>
            <li class="list-group-item">email: {{ email }}</li>
            <li class="list-group-item">총 가격: {{ price }}</li>
        </ul>
    </div>
    <br><script>
    var IMP = window.IMP;
    IMP.init('imp56421298');
    IMP.request_pay({
        pg: 'inicis', // version 1.1.0부터 지원.
        pay_method: 'phone',
        merchant_uid: 'merchant_' + new Date().getTime(),
        name: 'restaurant:{{ restaurant }},date:{{ information.date }},time:{{ information.time }}',
        amount: 100,
        buyer_email: '{{ email }}',
        buyer_name: '{{ name }}',
        buyer_tel: '{{ phone_number }}',
        m_redirect_url: 'https://www.yourdomain.com/payments/complete'
    }, function (rsp) {
        if ( rsp.success ) {
    	//[1] 서버단에서 결제정보 조회를 위해 jQuery ajax로 imp_uid 전달하기
    	jQuery.ajax({
    		url: "{% url 'reservations:views:save_all' %}", //cross-domain error가 발생하지 않도록 동일한 도메인으로 전송
    		type: 'POST',
    		dataType: 'json',
    		data: {
                csrfmiddlewaretoken: '{{ csrf_token }}',
	    		imp_uid : rsp.imp_uid,
                restaurant : '{{ restaurant_pk }}',
                information : '{{ information_pk }}',
                name : '{{ name }}',
                party : '{{ party }}',
                price : 100,
                phone_number : '{{ phone_number }}',
                email : '{{ email }}'
	    		//기타 필요한 데이터가 있으면 추가 전달
    		}
    	}).done(function(data) {
    		//[2] 서버에서 REST API로 결제정보확인 및 서비스루틴이 정상적인 경우
    		if ( data == 'true' ) {
    			var msg = '결제가 완료되었습니다.';
    			msg += '고유ID : ' + rsp.imp_uid;
    			msg += '상점 거래ID : ' + rsp.merchant_uid;
    			msg += '결제 금액 : ' + rsp.paid_amount;
    			msg += '카드 승인번호 : ' + rsp.apply_num;

    			alert(msg);
    		} else {
    			//[3] 아직 제대로 결제가 되지 않았습니다.
    			//[4] 결제된 금액이 요청한 금액과 달라 결제를 자동취소처리하였습니다.
    		}
    	});
    	window.location.replace('/reservations/views/payment/complete');
    } else {
        var msg = '결제에 실패하였습니다.';
        msg += '에러내용 : ' + rsp.error_msg;

        alert(msg);
        window.location.replace('/restaurants/{{ restaurant_pk }}');
    }

});
</script>

{% endblock %}

zinzi/templates/reservation/reservation.html
{% extends 'base.html' %}

{% block script %}
<script>
    $(document).ready(function(){
        var limit = null;
        $("#id_information").change(function(){
            var info = $("#id_information").val();
            var data = {
                info: info
            };
            $.ajax({
                    type: "GET",
                    url: "{{ build_absolute_uri }}",
                    data: data,
                    success: function(data){
                        limit = data["max_party"];
                    },
                    error: function(response, error){
                        console.log(response);
                        console.log(error);
                    }
                });

        });
        $("#id_party").change(function(){
            var party = $("#id_party").val();
            if(limit==null){
                alert("예약 시간을 선택하지 않았습니다.");
                $("#id_party").val(null)
            }
            else if(party>limit){
                alert("최대 허용숫자를 넘었습니다.");
                $("#id_party").val(limit)
            }
        })
    });

</script>
    {% endblock %}
{% block content %}
    {% include 'include/form-horizontal.html' with enctype=enctype form=form submit_text='예약' %}
{% endblock %}

zinzi/templates/reservation/reservation_check.html
{% extends 'base.html' %}

{% block content %}
    {% for reservation in reservations %}
        <div>
            <a href="{% url 'reservations:views:reservation_check_detail' pk=reservation.pk %}">
                <div>
                    {{ reservation.information }}
                </div>
                <div>
                    {{ reservation.name }}
                </div>
            </a>
        </div>
    {% endfor %}
{% endblock %}

zinzi/templates/reservation/reservation_check_detail.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <ul class="list-group" style="height: auto;">
            <li class="list-group-item">레스토랑 이름: {{ reservation.restaurant }}</li>
            <li class="list-group-item">날짜 및 시간: {{ reservation.information }}</li>
            <li class="list-group-item">예약자: {{ reservation.name }}</li>
            <li class="list-group-item">인원: {{ reservation.party }}</li>
            <li class="list-group-item">핸드폰 번호: {{ reservation.phone_number }}</li>
            <li class="list-group-item">email: {{ reservation.email }}</li>
            <li class="list-group-item">총 가격: {{ reservation.price }}</li>
            <li class="list-group-item">결제 상태: {{ reservation.status }}</li>
        </ul>
    </div>
    {% if request.user.profile.is_owner %}
        <div class="row">
            <ul class="list-group" style="height: auto;">
                <li class="list-group-item">결제번호: {{ payment.imp_uid }}</li>
            </ul>
        </div>
        {% if payment.paymentcancel %}
            <div class="row">
            <ul class="list-group" style="height: auto;">
                <li class="list-group-item">취소 이유: {{ payment.paymentcancel.reason }}</li>
            </ul>
            </div>
        {% endif %}
        {% if payment.reservation.status == 'cancel request' %}
            <div>
                <a class="btn btn-primary btn-block" href="{% url 'reservations:views:payment_cancel_confirm' pk=payment.pk %}">취소 확인</a>
            </div>
        {% endif %}
    {% else  %}
        {% if payment.reservation.status == 'paid' %}
            <div>
                <a class="btn btn-primary btn-block" href="{% url 'reservations:views:payment_cancel' pk=payment.pk %}">취소 요청</a>
            </div>
        {% endif %}
    {% endif %}
{% endblock %}