zinzi/accounts/urls.py
from django.conf.urls import url

from accounts import views

urlpatterns = [
    # Auth
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^signin/$', views.signin, name='signin'),
    url(r'^signout/$', views.signout, name='signout'),
    # url(r'^(?P<pk>\d+)/change-password/$', apis.ChangePasswordView.as_view(), name='change-password'),

    # Activate
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)/$', views.activate, name='activate'),
    url(r'^withdraw/$', views.withdraw, name='withdraw'),

    # Profile
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^update-profile/$', views.update_profile, name='update-profile'),
    # url(r'^(?P<pk>\d+)/owner-profile/$', apis.OwnerProfileView.as_view(), name='owner-profile'),
    # url(r'^(?P<pk>\d+)/preference/$', apis.PreferenceUpdate.as_view(), name='preference')
    # url(r'(?P<user_pk>\d+)/my-reservation/$' ),

    # Facebook
    # url(r'^facebook-login/$', apis.FacebookLoginView.as_view(), name='fb-login')
]

zinzi/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from config.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$', index, name='index'),

    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^restaurants/', include('restaurants.urls', namespace='restaurants')),
    url(r'^reservations/', include('reservations.urls', namespace='reservations')),
]
urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

zinzi/members/urls.py
from django.conf.urls import url

from members import views

urlpatterns = [
    url(r'^signup/$', views.Signup.as_view(), name='signup'),
    url(r'^signin/$', views.Signin.as_view(), name='signin'),
    # url(r'^profile/$', ),
    # url(r'(?P<user_pk>\d+)/my-reservation/$' ),
]

zinzi/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'favicon/favicon.ico' %}">

    <title>Zinzi</title>


    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-theme.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-datepicker/css/bootstrap-datepicker3.css' %}">
    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'bootstrap-datepicker/js/bootstrap-datepicker.js' %}"></script>
    <script src="{% static 'bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>



    {% block head %}
    {% endblock %}

</head>

<body>
{% include 'navbar.html' %}
<div class="container">


    {% block content %}

    {% endblock %}


</div>

        {% block script %}
        {% endblock %}


</body>
</html>

zinzi/templates/navbar.html
{% load staticfiles %}
<style>
    #navbar-container {
        background-color: #0f0f0f;
    }
    .navbar-header > a {
        color: white;
    }
    .navbar-header > a:hover {
        color: grey;
    }
    .navbar-header > a:focus {
        color: grey;
    }
    .navbar-collapse > ul > li > a {
        text-decoration: none;
        color: white;
    }
    .navbar-collapse > ul > li > a:focus {
        background-color: black;
        color: grey;
    }
    .navbar-collapse > ul > li > a:hover {
        background-color: black;
        color: grey;
    }
 </style>

<!-- Static navbar -->
<nav class="navbar navbar-static-top" id="navbar-container">
    <div class="container">
        <div class="navbar-header">
            <a id="index" class="navbar-brand navbar-a-tag icon" href="{% url 'index' %}"
               style="font-size:25px;">Zinzi</a>
            {#            <a class="navbar-brand navbar-a-tag" href="{% url 'home' %}" style="font-size:30px; padding-top:30px;"></a>#}
            <!-- <a class="navbar-brand navbar-a-tag" href="" style="font-size:22px;">Zinzi</a><br/> -->
        </div>


        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'accounts:signout' %}">로그아웃</a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:signin' %}">로그인</a></li>
                    {% endif %}
            </ul>
        </div>
    </div>
</nav>

zinzi/templates/test.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script type="text/javascript" src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
    <script type="text/javascript" src="https://service.iamport.kr/js/iamport.payment-1.1.5.js"></script>
</head>
<body>
<script>
    var IMP = window.IMP;
    IMP.init('imp56421298');
    IMP.request_pay({
        pg: 'inicis', // version 1.1.0부터 지원.
        pay_method: 'phone',
        merchant_uid: 'merchant_' + new Date().getTime(),
        name: '주문명:결제테스트',
        amount: 100,
        buyer_email: 'iamport@siot.do',
        buyer_name: '구매자이름',
        buyer_tel: '010-1234-5678',
        buyer_addr: '서울특별시 강남구 삼성동',
        buyer_postcode: '123-456',
        m_redirect_url: 'https://www.yourdomain.com/payments/complete'
    }, function (rsp) {
        if ( rsp.success ) {
    	//[1] 서버단에서 결제정보 조회를 위해 jQuery ajax로 imp_uid 전달하기
    	jQuery.ajax({
    		url: "/reservations/1/payment/", //cross-domain error가 발생하지 않도록 동일한 도메인으로 전송
    		type: 'POST',
    		dataType: 'json',
    		data: {
	    		imp_uid : rsp.imp_uid,
                price : 100
	    		//기타 필요한 데이터가 있으면 추가 전달
    		}
    	}).done(function(data) {
    		//[2] 서버에서 REST API로 결제정보확인 및 서비스루틴이 정상적인 경우
    		if ( everythings_fine ) {
    			var msg = '결제가 완료되었습니다.';
    			msg += '\n고유ID : ' + rsp.imp_uid;
    			msg += '\n상점 거래ID : ' + rsp.merchant_uid;
    			msg += '\결제 금액 : ' + rsp.paid_amount;
    			msg += '카드 승인번호 : ' + rsp.apply_num;

    			alert(msg);
    		} else {
    			//[3] 아직 제대로 결제가 되지 않았습니다.
    			//[4] 결제된 금액이 요청한 금액과 달라 결제를 자동취소처리하였습니다.
    		}
    	});
    } else {
        var msg = '결제에 실패하였습니다.';
        msg += '에러내용 : ' + rsp.error_msg;

        alert(msg);
    }
});
</script>
</body>
</html>

zinzi/templates/user_activate.html
<h3>진지한 외식 서비스 'Zinzi'에 가입해주셔서 감사합니다.</h3>

<p>아래 링크를 클릭하여 이메일 인증을 진행해주십시오.</p>
<a href="http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}"><button>이메일 인증</button></a>